/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.18.2.1 $ of : mfd-data-get.m2c,v $
 *
 * $Id:$
 *
 * @file dot11WtpIfTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef DOT11WTPIFTABLE_DATA_GET_H
#define DOT11WTPIFTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot11WtpIfTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * dot11WtpIfTable is subid 1 of wtpInterface.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.31656.6.1.1.3.1, length: 12
*/
    /*
     * indexes
     */
    int wtpMacAddr_map_wtpif(char **mib_wtpMacAddr_val_ptr_ptr, size_t *mib_wtpMacAddr_val_ptr_len_ptr, char *raw_wtpMacAddr_val_ptr, size_t raw_wtpMacAddr_val_ptr_len, int allow_realloc);
    int wtpIfIndex_map_wtpif(long *mib_wtpIfIndex_val_ptr, long raw_wtpIfIndex_val);

    int wtpMTU_map(long *mib_wtpMTU_val_ptr, long raw_wtpMTU_val);
    int wtpMTU_get( dot11WtpIfTable_rowreq_ctx *rowreq_ctx, long * wtpMTU_val_ptr );
    int wtpIfSpeed_map(u_long *mib_wtpIfSpeed_val_ptr, u_long raw_wtpIfSpeed_val);
    int wtpIfSpeed_get( dot11WtpIfTable_rowreq_ctx *rowreq_ctx, u_long * wtpIfSpeed_val_ptr );
    int wtpIfPhyAddr_map(char **mib_wtpIfPhyAddr_val_ptr_ptr, size_t *mib_wtpIfPhyAddr_val_ptr_len_ptr, char *raw_wtpIfPhyAddr_val_ptr, size_t raw_wtpIfPhyAddr_val_ptr_len, int allow_realloc);
    int wtpIfPhyAddr_get( dot11WtpIfTable_rowreq_ctx *rowreq_ctx, char **wtpIfPhyAddr_val_ptr_ptr, size_t *wtpIfPhyAddr_val_ptr_len_ptr );
    int wtpIfIntro_map(char **mib_wtpIfIntro_val_ptr_ptr, size_t *mib_wtpIfIntro_val_ptr_len_ptr, char *raw_wtpIfIntro_val_ptr, size_t raw_wtpIfIntro_val_ptr_len, int allow_realloc);
    int wtpIfIntro_get( dot11WtpIfTable_rowreq_ctx *rowreq_ctx, char **wtpIfIntro_val_ptr_ptr, size_t *wtpIfIntro_val_ptr_len_ptr );
    int wtpIfName_map(char **mib_wtpIfName_val_ptr_ptr, size_t *mib_wtpIfName_val_ptr_len_ptr, char *raw_wtpIfName_val_ptr, size_t raw_wtpIfName_val_ptr_len, int allow_realloc);
    int wtpIfName_get( dot11WtpIfTable_rowreq_ctx *rowreq_ctx, char **wtpIfName_val_ptr_ptr, size_t *wtpIfName_val_ptr_len_ptr );
    int wtpIfType_map(u_long *mib_wtpIfType_val_ptr, u_long raw_wtpIfType_val);
    int wtpIfType_get( dot11WtpIfTable_rowreq_ctx *rowreq_ctx, u_long * wtpIfType_val_ptr );
    int wtpIfAdminStatus_map(u_long *mib_wtpIfAdminStatus_val_ptr, u_long raw_wtpIfAdminStatus_val);
    int wtpIfAdminStatus_get( dot11WtpIfTable_rowreq_ctx *rowreq_ctx, u_long * wtpIfAdminStatus_val_ptr );
    int wtpIfOperStatus_map(u_long *mib_wtpIfOperStatus_val_ptr, u_long raw_wtpIfOperStatus_val);
    int wtpIfOperStatus_get( dot11WtpIfTable_rowreq_ctx *rowreq_ctx, u_long * wtpIfOperStatus_val_ptr );
    int wtpIfLastChange_map(u_long *mib_wtpIfLastChange_val_ptr, u_long raw_wtpIfLastChange_val);
    int wtpIfLastChange_get( dot11WtpIfTable_rowreq_ctx *rowreq_ctx, u_long * wtpIfLastChange_val_ptr );
    int wtpIfUplinkRealtimeRate_map(u_long *mib_wtpIfUplinkRealtimeRate_val_ptr, u_long raw_wtpIfUplinkRealtimeRate_val);
    int wtpIfUplinkRealtimeRate_get( dot11WtpIfTable_rowreq_ctx *rowreq_ctx, u_long * wtpIfUplinkRealtimeRate_val_ptr );
    int wtpIfDownlinkRealtimeRate_map(u_long *mib_wtpIfDownlinkRealtimeRate_val_ptr, u_long raw_wtpIfDownlinkRealtimeRate_val);
    int wtpIfDownlinkRealtimeRate_get( dot11WtpIfTable_rowreq_ctx *rowreq_ctx, u_long * wtpIfDownlinkRealtimeRate_val_ptr );
    int wtpIfUplinkRealtimeKbyteRate_get( dot11WtpIfTable_rowreq_ctx *rowreq_ctx, u_long * wtpIfUplinkRealtimeKbyteRate_val_ptr );
    int wtpIfDownlinkRealtimeKbyteRate_get( dot11WtpIfTable_rowreq_ctx *rowreq_ctx, u_long * wtpIfDownlinkRealtimeKbyteRate_val_ptr );
    int wtpipv6IfInReceivesPkts_get( dot11WtpIfTable_rowreq_ctx *rowreq_ctx, U64 * wtpipv6IfInReceivesPkts_val_ptr );
    int wtpipv6IfInHdrErrorsPkts_get( dot11WtpIfTable_rowreq_ctx *rowreq_ctx, U64 * wtpipv6IfInHdrErrorsPkts_val_ptr );
    int wtpipv6IfInTooBigErrorsPkts_get( dot11WtpIfTable_rowreq_ctx *rowreq_ctx, U64 * wtpipv6IfInTooBigErrorsPkts_val_ptr );
    int wtpipv6IfInNoRoutesPkts_get( dot11WtpIfTable_rowreq_ctx *rowreq_ctx, U64 * wtpipv6IfInNoRoutesPkts_val_ptr );
    int wtpipv6IfInAddrErrorsPkts_get( dot11WtpIfTable_rowreq_ctx *rowreq_ctx, U64 * wtpipv6IfInAddrErrorsPkts_val_ptr );
    int wtpipv6IfInUnknownProtosPkts_get( dot11WtpIfTable_rowreq_ctx *rowreq_ctx, U64 * wtpipv6IfInUnknownProtosPkts_val_ptr );
    int wtpipv6IfInTruncatedPkts_get( dot11WtpIfTable_rowreq_ctx *rowreq_ctx, U64 * wtpipv6IfInTruncatedPkts_val_ptr );
    int wtpipv6IfInDiscardsPkts_get( dot11WtpIfTable_rowreq_ctx *rowreq_ctx, U64 * wtpipv6IfInDiscardsPkts_val_ptr );
    int wtpipv6IfInDeliversPkts_get( dot11WtpIfTable_rowreq_ctx *rowreq_ctx, U64 * wtpipv6IfInDeliversPkts_val_ptr );
    int wtpipv6IfOutForwDatagramsPkts_get( dot11WtpIfTable_rowreq_ctx *rowreq_ctx, U64 * wtpipv6IfOutForwDatagramsPkts_val_ptr );
    int wtpipv6IfOutRequestsPkts_get( dot11WtpIfTable_rowreq_ctx *rowreq_ctx, U64 * wtpipv6IfOutRequestsPkts_val_ptr );
    int wtpipv6IfOutDiscardsPkts_get( dot11WtpIfTable_rowreq_ctx *rowreq_ctx, U64 * wtpipv6IfOutDiscardsPkts_val_ptr );
    int wtpipv6IfOutFragOKsPkts_get( dot11WtpIfTable_rowreq_ctx *rowreq_ctx, U64 * wtpipv6IfOutFragOKsPkts_val_ptr );
    int wtpipv6IfOutFragFailsPkts_get( dot11WtpIfTable_rowreq_ctx *rowreq_ctx, U64 * wtpipv6IfOutFragFailsPkts_val_ptr );
    int wtpipv6IfOutFragCreatesPkts_get( dot11WtpIfTable_rowreq_ctx *rowreq_ctx, U64 * wtpipv6IfOutFragCreatesPkts_val_ptr );
    int wtpipv6IfReasmReqdsPkts_get( dot11WtpIfTable_rowreq_ctx *rowreq_ctx, U64 * wtpipv6IfReasmReqdsPkts_val_ptr );
    int wtpipv6IfReasmOKsPkts_get( dot11WtpIfTable_rowreq_ctx *rowreq_ctx, U64 * wtpipv6IfReasmOKsPkts_val_ptr );
    int wtpipv6IfReasmFailsPkts_get( dot11WtpIfTable_rowreq_ctx *rowreq_ctx, U64 * wtpipv6IfReasmFailsPkts_val_ptr );
    int wtpipv6IfInMcastPkts_get( dot11WtpIfTable_rowreq_ctx *rowreq_ctx, U64 * wtpipv6IfInMcastPkts_val_ptr );
    int wtpipv6IfOutMcastPkts_get( dot11WtpIfTable_rowreq_ctx *rowreq_ctx, U64 * wtpipv6IfOutMcastPkts_val_ptr );

int dot11WtpIfTable_indexes_set_tbl_idx(dot11WtpIfTable_mib_index *tbl_idx, char *wtpMacAddr_val_ptr,  size_t wtpMacAddr_val_ptr_len, long wtpIfIndex_val);
int dot11WtpIfTable_indexes_set(dot11WtpIfTable_rowreq_ctx *rowreq_ctx, char *wtpMacAddr_val_ptr,  size_t wtpMacAddr_val_ptr_len, long wtpIfIndex_val);




#ifdef __cplusplus
}
#endif

#endif /* DOT11WTPIFTABLE_DATA_GET_H */
/** @} */
